// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApNxwscPiZtHnIfG75_xTduHDvZ_231dA',
    appId: '1:859100727065:web:048fa006efa287c021a788',
    messagingSenderId: '859100727065',
    projectId: 'scrapyart-79035',
    authDomain: 'scrapyart-79035.firebaseapp.com',
    storageBucket: 'scrapyart-79035.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6OhHOhi6GnRFB1rVS0wNZ2Llm6iTgHw0',
    appId: '1:859100727065:android:65b1df3e752c52a521a788',
    messagingSenderId: '859100727065',
    projectId: 'scrapyart-79035',
    storageBucket: 'scrapyart-79035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaCJicNAWTNoFwP_ms2SjH-BFgao4xQ3U',
    appId: '1:859100727065:ios:5d8c073f5efab88421a788',
    messagingSenderId: '859100727065',
    projectId: 'scrapyart-79035',
    storageBucket: 'scrapyart-79035.appspot.com',
    iosBundleId: 'com.example.scrapyart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaCJicNAWTNoFwP_ms2SjH-BFgao4xQ3U',
    appId: '1:859100727065:ios:93b07f61206ed8d021a788',
    messagingSenderId: '859100727065',
    projectId: 'scrapyart-79035',
    storageBucket: 'scrapyart-79035.appspot.com',
    iosBundleId: 'com.example.scrapyart.RunnerTests',
  );
}
